- action:
  - data:
      entity_id: switch.front_yard_light_switch
    service: homeassistant.turn_on
  - data:
      entity_id: switch.decorations_switch
    service: homeassistant.turn_on
  alias: Sunset
  condition: []
  id: '1516820458704'
  trigger:
  - event: sunset
    platform: sun
- action:
  - data:
      entity_id: switch.front_yard_light_switch
    service: homeassistant.turn_off
  alias: Sunrise
  condition: []
  id: '1516820501600'
  trigger:
  - event: sunrise
    platform: sun
- action:
  - data:
      name: dark_theme
    service: frontend.set_theme
  alias: Set Theme
  condition: []
  id: '1516896365641'
  trigger:
  - event: start
    platform: homeassistant
- action:
  - data:
      entity_id: switch.decorations_switch
    service: homeassistant.turn_off
  - data:
      entity_id: group.all_locks
    service: lock.lock
  alias: Good Night
  condition: []
  id: '1516932976861'
  trigger:
  - at: '23:59'
    platform: time
