version: '2'
services:

  db:
     image: hypriot/rpi-mysql:5.5
     volumes:
        - /home/pi/docker/mssql//mysql:/var/lib/mysql
     restart: always
     expose:
       - "3306"
     environment:
       MYSQL_ROOT_PASSWORD: '<<redacted>>'
       MYSQL_DATABASE: '<<redacted>>'
       MYSQL_USER: '<<redacted>>'
       MYSQL_PASSWORD: '<<redacted>>'

  web:
    depends_on:
       - db
    image: homeassistant/raspberrypi3-homeassistant
    volumes:
      - /home/pi/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
